### ISSUE TITLE
Enable versioning

### ISSUE THREAD

**Issue by muuvmuuv** [philipbelesky/inter-ui#20]
It is common to set cache headers for resources like fonts. An example is by adding a `?v=1.19.2` at the end of a font file. But inter-ui is not doing any versioning, so my browser would never use the potential newer server files.

This should be a simple implementation since you are doing it by hand you can just create a new variable that you and importers can use.

**Comment by philipbelesky** [comment]
Hey,thanks for the suggestion, that totally makes sense. I've added these in and rolled a point release. Let me know if you have any issues with it.
