### ISSUE TITLE
CSS files

### ISSUE THREAD

**Issue by maximeg** [philipbelesky/inter-ui#23]
Hi,

Longtime user, in some projects, we ditched sass for pure css + postcss (+ tailwind).

Can we have `inter-latin.css` and `inter-hinted-latin.css` files part of the package ?
As we have already `inter.css` and `inter-hinted.css`.

This would be neat to save a few bytes instead of reintroducing sass just for that.

(also thanks for defaulting to `font-display: swap;` ;) )

**Comment by philipbelesky** [comment]
Thanks for the suggestion, I've added the files in the just-released `3.19.1`. Let me know if that doesn't work with your project!

**Comment by maximeg** [comment]
Wow thanks for the reactivity!

Somehow it lacks the `'Inter var'` family in `inter-latin.css`

**Comment by maximeg** [comment]
I created a PR to be able to run `npm run generate-css` and ease things.
