### ISSUE TITLE
Please update to 4.0

### ISSUE THREAD

**Issue by Leonya** [philipbelesky/inter-ui#38]
Version 4.0 is out, please update.

**Comment by philipbelesky** [comment]
I'll update this when I have time; probably in the next fortnight. At a glance, the existing formats and filenames from 3.X have changed so I'll need to update and check my build process for subsetting. Since this is a major version, and the formats have changed slightly, i'll probably also take the chance to rationalise the folder paths and file names.

**Comment by philipbelesky** [comment]
I think this is ready, I've published a RC that you can install with `npm install inter-ui@next`

I am a little hesitant to do a full-rollout release as the new font families have meant renaming a bunch of folders, font-family's, etc. I think the CSS/SASS has been updated to match, but I don't have any active projects using those methods. A quick ping to some past contributors who may want to check things out and verify things: @manuelmeister @maximeg @kraftner

**Comment by Leonya** [comment]
I can confirm it works. Haven't tested the CSS/SASS files either because I have my own CSS, but from a quick glance they look correct. Sent you a small PR with wording fixes.

**Comment by GabsEdits** [comment]
> I think this is ready, I've published a RC that you can install with `npm install inter-ui@next`
> 
> I am a little hesitant to do a full-rollout release as the new font families have meant renaming a bunch of folders, font-family's, etc. I think the CSS/SASS has been updated to match, but I don't have any active projects using those methods. A quick ping to some past contributors who may want to check things out and verify things: @manuelmeister @maximeg @kraftner

I've updated my project to v4 and imported the CSS using JS, everthing seems fine, just like the local fonts I had from the source.

**Comment by philipbelesky** [comment]
Great, thanks everyone. I've rollout out `4.0.0`
