### ISSUE TITLE
Add a way to change the `font-display` property

### ISSUE THREAD

**Issue by Calinou** [philipbelesky/inter-ui#4]
As described in [this issue](https://github.com/rsms/inter/issues/97), there should be a way to let the user set the [`font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) property according to their preferences.

Perhaps we could add a Sass file where you can set a variable before importing it, in addition to the current CSS file (where it wouldn't be customizable).

**Comment by philipbelesky** [comment]
Hey, thanks for adding this. In order to minimise the burden of tracking the main repo I've tried to set it up such that updating the files is as easy as possible. That said this sounds like an important use case and I'd be happy to accept a PR that adds a Sass file.
