### ISSUE TITLE
Lower required node version to say v. 18

### ISSUE THREAD

**Issue by lassegit** [philipbelesky/inter-ui#40]
Wanted to add Inter v.4 to my NextJS [site](https://www.sqlai.ai/) but Inter-ui requires at least Node v. 20. My hosting only support Node version up to v. 18. Is there a reason for this?

It recently got added in this PR (https://github.com/philipbelesky/inter-ui/commit/eaace05930fd3752469acb393d6d993538cc4e5d).

**Comment by philipbelesky** [comment]
Sorry for the oversight! I have reduced the version required to 16 and issued a `4.0.1`
