### ISSUE TITLE
Hinted CSS/SCSS references non-existent variational fonts

### ISSUE THREAD

**Issue by danpalmer** [philipbelesky/inter-ui#8]
The "hinted" files, CSS and SCSS variants, reference the following non-existent files:

- Inter (web hinted)/Inter.var.woff2
- Inter (web hinted)/Inter-italic.var.woff2
- Inter (web hinted)/Inter-upright.var.woff2

This causes build failures when using a packager such as webpack.

**Comment by philipbelesky** [comment]
@danpalmer thanks for the report, this should be addressed in the latest hotfix.
